## **1. Comprendre BERT et XLM-RoBERTa**

### Introduction aux modèles de transformateurs

Les modèles de Transformers sont une architecture de réseau neuronal qui a révolutionné le traitement du langage naturel (NLP). Ils sont particulièrement efficaces pour gérer les données séquentielles, comme le texte, grâce à leur mécanisme d'auto-attention. Ce mécanisme permet au modèle de peser l'importance des différentes parties de la séquence d'entrée lors du traitement de chaque élément.

### BERT (Bidirectional Encoder Representations from Transformers)

BERT est un modèle de Transformers pré-entraîné développé par Google. Il est **bidirectionnel**, c'est-à-dire qu'il prend en compte le contexte des mots à la fois à gauche et à droite pour comprendre le sens d'un mot. BERT est entraîné sur deux tâches principales :

1.  **Modélisation du langage masqué (Masked Language Model - MLM)** : Le modèle prédit des mots masqués aléatoirement dans une séquence.
2.  **Prédiction de la phrase suivante (Next Sentence Prediction - NSP)** : Le modèle prédit si deux phrases données sont consécutives ou non.

BERT a plusieurs versions pré-entraînées (par exemple, `bert-base-uncased`, `bert-large-cased`) qui varient en taille et en type de corpus d'entraînement.

### XLM-RoBERTa (Cross-lingual Language Model - Robustly Optimized BERT Pretraining Approach)

XLM-RoBERTa est une version multilingue de RoBERTa, qui est lui-même une version optimisée de BERT. L'objectif principal de XLM-RoBERTa est de construire un modèle de langage qui fonctionne bien pour de nombreuses langues simultanément. Il est entraîné sur un très grand corpus multilingue (plus de 100 langues) et n'utilise pas la tâche NSP. Au lieu de cela, il se concentre uniquement sur la tâche MLM, mais sur des corpus de texte beaucoup plus importants.

L'avantage de XLM-RoBERTa est sa capacité à transférer des connaissances entre les langues, ce qui le rend très utile pour des tâches basées sur la langue où les ressources sont limitées.

## **2. Tokenisation du texte**

La tokenisation est le processus de décomposition d'un texte en unités plus petites appelées "jetons" (tokens). Pour les modèles de Tranformers comme BERT et XLM-RoBERTa, cela implique souvent l'utilisation de sous-mots pour gérer les mots inconnus et réduire la taille du vocabulaire.

Les tokeniseurs de **transformers** ajoutent également des jetons spéciaux au début et à la fin des séquences (par exemple, **[CLS]** Et **[SEP]** pour BERT) et génèrent des masques d'attention et des IDs de type de segment nécessaires à l'entrée du modèle.

In [1]:
# Installation de la library transformers s'il n'est pas encore installer
!pip install transformers

# Importation des library necessaires
from transformers import BertTokenizer, XLMRobertaTokenizer

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.19.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [2]:
# Initialisation des tokens
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
xlm_roberta_tokenizer = XLMRobertaTokenizer.from_pretrained('xlm-roberta-base')

print("Tokenizers initialized.")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

Tokenizers initialized.

### Tokenisation d'une phrase unique

Nous allons tokeniser une phrase simple et observer les **input_ids**, **attention_mask**.

In [10]:
sentence = "Yo, i'm verry happy today?"

# Tokenisation avec la fonction tokeniser de BERT
bert_encoding = bert_tokenizer(
    sentence,
    add_special_tokens=True,  # Add '[CLS]' and '[SEP]'
    max_length=64,           # Pad/truncate to a fixed length
    padding='max_length',    # Pad to max_length
    return_attention_mask=True, # Return attention mask
    return_tensors='pt'      # Return PyTorch tensors
)

print("BERT Tokenization (single sentence):")
print(f"  Input IDs: {bert_encoding['input_ids']}")
print(f"  Attention Mask: {bert_encoding['attention_mask']}")
print(f"  Decoded: {bert_tokenizer.decode(bert_encoding['input_ids'][0])}")

print("\n" + "="*50 + "\n")

# Tokenisation avec la fonction tokeniser de Roberta
xlm_roberta_encoding = xlm_roberta_tokenizer(
    sentence,
    add_special_tokens=True,  # Add '<s>' and '</s>'
    max_length=64,           # Pad/truncate to a fixed length
    padding='max_length',    # Pad to max_length
    return_attention_mask=True, # Return attention mask
    return_tensors='pt'      # Return PyTorch tensors
)

print("XLM-RoBERTa Tokenization (single sentence):")
print(f"  Input IDs: {xlm_roberta_encoding['input_ids']}")
print(f"  Attention Mask: {xlm_roberta_encoding['attention_mask']}")
print(f"  Decoded: {xlm_roberta_tokenizer.decode(xlm_roberta_encoding['input_ids'][0])}")

BERT Tokenization (single sentence):
  Input IDs: tensor([[  101, 10930,  1010,  1045,  1005,  1049,  2310, 12244,  3407,  2651,
          1029,   102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]])
  Attention Mask: tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
  Decoded: [CLS] yo, i ' m verry happy today? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]

==================================================

XLM-RoBERTa Tokenization (single sentence):
  Input IDs: tensor([[    0,  6949,     4,    17,    25,    39,   493,  1294, 17723, 18925,
            32,     2,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1]])
  Attention Mask: tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
  Decoded: <s> Yo, i'm verry happy today?</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>

### Tokenisation de deux phrases

Nous allons maintenant tokeniser une paire de phrases. Pour BERT, cela inclura également `token_type_ids` pour distinguer les deux phrases.

In [11]:
sentence1 = "This dog is my dog."
sentence2 = "Why he follow you?."

# Tokenize with BERT tokenizer for two sentences
bert_pair_encoding = bert_tokenizer(
    sentence1,
    sentence2,
    add_special_tokens=True,
    max_length=64,
    padding='max_length',
    return_attention_mask=True,
    return_token_type_ids=True, # Return token type IDs for BERT
    return_tensors='pt'
)

print("BERT Tokenization (two sentences):")
print(f"  Input IDs: {bert_pair_encoding['input_ids']}")
print(f"  Attention Mask: {bert_pair_encoding['attention_mask']}")
print(f"  Token Type IDs: {bert_pair_encoding['token_type_ids']}") # 0 for first sentence, 1 for second
print(f"  Decoded: {bert_tokenizer.decode(bert_pair_encoding['input_ids'][0])}")

print("\n" + "="*50 + "\n")

# Tokenize with XLM-RoBERTa tokenizer for two sentences
# XLM-RoBERTa typically doesn't use token_type_ids for sentence separation like BERT
xlm_roberta_pair_encoding = xlm_roberta_tokenizer(
    sentence1,
    sentence2,
    add_special_tokens=True,
    max_length=64,
    padding='max_length',
    return_attention_mask=True,
    return_tensors='pt'
)

print("XLM-RoBERTa Tokenization (two sentences):")
print(f"  Input IDs: {xlm_roberta_pair_encoding['input_ids']}")
print(f"  Attention Mask: {xlm_roberta_pair_encoding['attention_mask']}")
print(f"  Decoded: {xlm_roberta_tokenizer.decode(xlm_roberta_pair_encoding['input_ids'][0])}")

BERT Tokenization (two sentences):
  Input IDs: tensor([[ 101, 2023, 3899, 2003, 2026, 3899, 1012,  102, 2339, 2002, 3582, 2017,
         1029, 1012,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]])
  Attention Mask: tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
  Token Type IDs: tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
  Decoded: [CLS] this dog is my dog. [SEP] why he follow you?. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]

==================================================

XLM-RoBERTa Tokenization (two sentences):
  Input IDs: tensor([[    0,  3293, 10269,    83,   759, 10269,     5,     2,     2, 44084,
           764, 28960,   398,    32,     5,     2,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1]])
  Attention Mask: tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
  Decoded: <s> This dog is my dog.</s></s> Why he follow you?.</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>

## **3. Préparation des données d'entrée pour le modèle**

Pour que les modèles de transformateurs puissent traiter le texte correctement, les entrées doivent être dans un format spécifique, ce qui implique plusieurs étapes clés :

### Token Spéciaux

Les modèles Transformers utilisent des tokens spéciaux pour signaler le début et la fin d'une séquence, ainsi que pour séparer plusieurs segments de texte (comme deux phrases). Ces tokens sont essentiels pour le bon fonctionnement des modèles.

*   **Pour BERT :**
    *   **[CLS]** (Class Token) : C'est le premier token de chaque séquence. L'état caché correspondant à ce token est souvent utilisé comme représentation agrégée de l'ensemble de la séquence pour des tâches de classification.
    *   **[SEP]** (Separator Token) : Utilisé pour indiquer la fin d'une phrase ou pour séparer deux phrases différentes dans une entrée.

*   **Pour XLM-RoBERTa :**
    *   **`<s>`** (Sentence Start) : Marque le début d'une séquence ou d'une phrase.
    *   **`</s>`** (Sentence End) : Marque la fin d'une séquence ou d'une phrase. Lorsqu'il y a deux phrases, un **</s>** est inséré entre elles et un autre à la fin de la seconde phrase.

### Masque d'Attention (`attention_mask`)

Le **attention_mask** est une séquence de 0 et de 1 qui indique au modèle quels jetons doivent être pris en compte (1) et quels jetons doivent être ignorés (0). Ceci est crucial pour le remplissage (`padding`) : lorsque des séquences sont rendues de la même longueur en ajoutant des tokens de remplissage, l'**attention_mask** garantit que le modèle ne porte pas attention à ces tokens de remplissage, qui n'ont aucune signification sémantique.

### Longueur Maximale et Remplissage/Troncation

Les modèles de Transformers ont une longueur d'entrée maximale fixe (par exemple, 512 tokens pour la plupart des versions de BERT). Les phrases plus courtes sont complétées avec des tokens de remplissage (**[PAD]** ou **<pad>**) jusqu'à cette longueur maximale, et les phrases plus longues sont tronquées. L'attention_mask gère les tokens de remplissage.

In [12]:
# Afficher les tokens spéciaux pour BERT
print("BERT Special Tokens Map:")
print(bert_tokenizer.special_tokens_map)
print(f"BERT Vocabulary Size: {bert_tokenizer.vocab_size}")

print("\n" + "="*50 + "\n")

# Afficher les tokens spéciaux pour XLM-RoBERTa
print("XLM-RoBERTa Special Tokens Map:")
print(xlm_roberta_tokenizer.special_tokens_map)
print(f"XLM-RoBERTa Vocabulary Size: {xlm_roberta_tokenizer.vocab_size}")

BERT Special Tokens Map:
{'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}
BERT Vocabulary Size: 30522

==================================================

XLM-RoBERTa Special Tokens Map:
{'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}
XLM-RoBERTa Vocabulary Size: 250002

## **4. Chargement et exploration de l'ensemble de données**

In [13]:
import pandas as pd

In [14]:
df_test = pd.read_csv("test.csv")
df_train = pd.read_csv("train.csv")

In [17]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5195 entries, 0 to 5194
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          5195 non-null   object
 1   premise     5195 non-null   object
 2   hypothesis  5195 non-null   object
 3   lang_abv    5195 non-null   object
 4   language    5195 non-null   object
dtypes: object(5)
memory usage: 203.1+ KB

In [18]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12120 entries, 0 to 12119
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          12120 non-null  object
 1   premise     12120 non-null  object
 2   hypothesis  12120 non-null  object
 3   lang_abv    12120 non-null  object
 4   language    12120 non-null  object
 5   label       12120 non-null  int64
dtypes: int64(1), object(5)
memory usage: 568.3+ KB

In [15]:
df_test.head()

,id,premise,hypothesis,lang_abv,language
0,c6d58c3f69,بکس، کیسی، راہیل، یسعیاہ، کیلی، کیلی، اور کولم...,"کیسی کے لئے کوئی یادگار نہیں ہوگا, کولمین ہائی...",ur,Urdu
1,cefcc82292,هذا هو ما تم نصحنا به.,عندما يتم إخبارهم بما يجب عليهم فعله ، فشلت ال...,ar,Arabic
2,e98005252c,et cela est en grande partie dû au fait que le...,Les mères se droguent.,fr,French
3,58518c10ba,与城市及其他公民及社区组织代表就IMA的艺术发展进行对话&amp,IMA与其他组织合作，因为它们都依靠共享资金。,zh,Chinese
4,c32b0d16df,Она все еще была там.,"Мы думали, что она ушла, однако, она осталась.",ru,Russian

In [16]:
df_train.head()

,id,premise,hypothesis,lang_abv,language,label
0,5130fd2cb5,and these comments were considered in formulat...,The rules developed in the interim were put to...,en,English,0
1,5b72532a0b,These are issues that we wrestle with in pract...,Practice groups are not permitted to work on t...,en,English,2
2,3931fbe82a,Des petites choses comme celles-là font une di...,J'essayais d'accomplir quelque chose.,fr,French,0
3,5622f0c60b,you know they can't really defend themselves l...,They can't defend themselves because of their ...,en,English,0
4,86aaa48b45,ในการเล่นบทบาทสมมุติก็เช่นกัน โอกาสที่จะได้แสด...,เด็กสามารถเห็นได้ว่าชาติพันธุ์แตกต่างกันอย่างไร,th,Thai,1

In [22]:
df_test.shape, df_train.shape

((5195, 5), (12120, 6))

## 5. Création de plis de validation croisée

Pour évaluer la performance de notre modèle de manière robuste et éviter le surapprentissage, nous allons utiliser une validation croisée à k plis. **StratifiedKFold** est choisi pour maintenir la proportion des classes dans chaque pli, ce qui est crucial pour les tâches de classification.

Nous allons créer 5 plis (**n_splits=5**), mélanger les données (**shuffle=True**) pour garantir la randomisation, et fixer un **random_state** pour la reproductibilité.

In [25]:
from sklearn.model_selection import StratifiedKFold

# Initialisation de StratifiedKFold
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Listes pour stocker les DataFrames d'entraînement et de validation pour chaque pli
train_folds = []
val_folds = []

print("Génération des plis de validation croisée...")

# Split the training data into folds
for fold, (train_index, val_index) in enumerate(kf.split(df_train, df_train['label'])):
    print(f"Processing Fold {fold+1}/")

    # Create train and validation sets for the current fold
    fold_train_df = df_train.iloc[train_index].reset_index(drop=True)
    fold_val_df = df_train.iloc[val_index].reset_index(drop=True)

    train_folds.append(fold_train_df)
    val_folds.append(fold_val_df)

Generating cross-validation folds...
Processing Fold 1/
Processing Fold 2/
Processing Fold 3/
Processing Fold 4/
Processing Fold 5/

In [26]:

print("Cross-validation folds created successfully!")
print(f"Number of training folds: {len(train_folds)}")
print(f"Number of validation folds: {len(val_folds)}")

Cross-validation folds created successfully!
Number of training folds: 5
Number of validation folds: 5

In [27]:

# Display shape of the first training and validation fold
print(f"Shape of first training fold: {train_folds[0].shape}")
print(f"Shape of first validation fold: {val_folds[0].shape}")

Shape of first training fold: (9696, 6)
Shape of first validation fold: (2424, 6)

In [29]:

# Display the label distribution in the first fold to verify stratification
print("\nLabel distribution in first training fold:")
display(train_folds[0]['label'].value_counts(normalize=True))

Label distribution in first training fold:

label
0    0.344472
2    0.335396
1    0.320132
Name: proportion, dtype: float64

In [ ]:
print("\nLabel distribution in first validation fold:")
display(val_folds[0]['label'].value_counts(normalize=True))